# Generated by Django 2.2.1 on 2019-09-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trax_vehicle_manager_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='chalak_malal',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=100),
        ),
    ]
